version: "3"

services:
  gotenberg:
    container_name: pdfserver
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    ports:
      - "3030:3000"
  
  repoter:
    container_name: repotman
    image: ghcr.io/onos9/resultgenie:latest
    restart: unless-stopped
    ports:
      - "3031:3000"
    volumes:
      - ./template:/app/template
      - ./generated:/app/generated